-- #%L
-- co
-- %%
-- Copyright (C) 2024 - 2025 Jinahya, Inc.
-- %%
-- Licensed under the Apache License, Version 2.0 (the "License");
-- you may not use this file except in compliance with the License.
-- You may obtain a copy of the License at
-- 
--      http://www.apache.org/licenses/LICENSE-2.0
-- 
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.
-- #L%
---
--
-- create table CO.INVENTORY
-- (
--     INVENTORY_ID      NUMBER generated by default on null as identity
--         constraint INVENTORY_PK
--             primary key,
--     STORE_ID          NUMBER not null
--         constraint INVENTORY_STORE_ID_FK
--             references CO.STORES,
--     PRODUCT_ID        NUMBER not null
--         constraint INVENTORY_PRODUCT_ID_FK
--             references CO.PRODUCTS,
--     PRODUCT_INVENTORY NUMBER not null,
--     constraint INVENTORY_STORE_PRODUCT_U
--         unique (STORE_ID, PRODUCT_ID)
-- )
-- /
--
-- comment on table CO.INVENTORY is 'Details of the quantity of stock available for products at each location'
-- /
--
-- comment on column CO.INVENTORY.INVENTORY_ID is 'Auto-incrementing primary key'
-- /
--
-- comment on column CO.INVENTORY.STORE_ID is 'Which location the goods are located at'
-- /
--
-- comment on column CO.INVENTORY.PRODUCT_ID is 'Which item this stock is for'
-- /
--
-- comment on column CO.INVENTORY.PRODUCT_INVENTORY is 'The current quantity in stock'
-- /
--
-- create index CO.INVENTORY_PRODUCT_ID_I
--     on CO.INVENTORY (PRODUCT_ID)
-- /


-- -------------------------------------------------------------------------------------------------------- INVENTORY_ID


-- ------------------------------------------------------------------------------------------------------------ STORE_ID


-- ---------------------------------------------------------------------------------------------------------- PRODUCT_ID


-- --------------------------------------------------------------------------------------------------- PRODUCT_INVENTORY
SELECT *
FROM INVENTORY
WHERE PRODUCT_INVENTORY < 0
;

SELECT STORE_ID, PRODUCT_ID, MAX(PRODUCT_INVENTORY)
FROM INVENTORY
GROUP BY STORE_ID, PRODUCT_ID
;

SELECT spx.*, s.STORE_NAME, p.PRODUCT_NAME
FROM (SELECT STORE_ID, PRODUCT_ID, MAX(PRODUCT_INVENTORY)
      FROM INVENTORY
      GROUP BY STORE_ID, PRODUCT_ID) spx
         JOIN STORES s ON spx.STORE_ID = s.STORE_ID
         JOIN CO.PRODUCTS p ON spx.PRODUCT_ID = p.PRODUCT_ID
;

SELECT spx.*, s.STORE_NAME, p.PRODUCT_NAME
FROM (SELECT STORE_ID, PRODUCT_ID, PRODUCT_INVENTORY
      FROM INVENTORY
      WHERE PRODUCT_INVENTORY = 0) spx
         JOIN STORES s ON spx.STORE_ID = s.STORE_ID
         JOIN CO.PRODUCTS p ON spx.PRODUCT_ID = p.PRODUCT_ID
;
