-- #%L
-- co
-- %%
-- Copyright (C) 2024 - 2025 Jinahya, Inc.
-- %%
-- Licensed under the Apache License, Version 2.0 (the "License");
-- you may not use this file except in compliance with the License.
-- You may obtain a copy of the License at
-- 
--      http://www.apache.org/licenses/LICENSE-2.0
-- 
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.
-- #L%
---
--
-- create table CO.SHIPMENTS
-- (
--     SHIPMENT_ID      NUMBER generated by default on null as identity
--         constraint SHIPMENTS_PK
--             primary key,
--     STORE_ID         NUMBER             not null
--         constraint SHIPMENTS_STORE_ID_FK
--             references CO.STORES,
--     CUSTOMER_ID      NUMBER             not null
--         constraint SHIPMENTS_CUSTOMER_ID_FK
--             references CO.CUSTOMERS,
--     DELIVERY_ADDRESS VARCHAR2(512 char) not null,
--     SHIPMENT_STATUS  VARCHAR2(100 char) not null
--         constraint SHIPMENT_STATUS_C
--             check (shipment_status in
--                    ('CREATED', 'SHIPPED', 'IN-TRANSIT', 'DELIVERED'))
-- )
-- /
--
-- comment on table CO.SHIPMENTS is 'Details of where ordered goods will be delivered'
-- /
--
-- comment on column CO.SHIPMENTS.SHIPMENT_ID is 'Auto-incrementing primary key'
-- /
--
-- comment on column CO.SHIPMENTS.STORE_ID is 'Which location the goods will be transported from'
-- /
--
-- comment on column CO.SHIPMENTS.CUSTOMER_ID is 'Who this shipment is for'
-- /
--
-- comment on column CO.SHIPMENTS.DELIVERY_ADDRESS is 'Where the goods will be transported to'
-- /
--
-- comment on column CO.SHIPMENTS.SHIPMENT_STATUS is 'The current status of the shipment. Valid values are:
-- CREATED - the shipment is ready for order assignment
-- SHIPPED - the goods have been dispatched
-- IN-TRANSIT - the goods are en-route to their destination
-- DELIVERED - the good have arrived at their destination'
-- /
--
-- create index CO.SHIPMENTS_STORE_ID_I
--     on CO.SHIPMENTS (STORE_ID)
-- /
--
-- create index CO.SHIPMENTS_CUSTOMER_ID_I
--     on CO.SHIPMENTS (CUSTOMER_ID)
-- /


-- --------------------------------------------------------------------------------------------------------- SHIPMENT_ID

-- ------------------------------------------------------------------------------------------------------------ STORE_ID

-- --------------------------------------------------------------------------------------------------------- CUSTOMER_ID

-- ---------------------------------------------------------------------------------------------------- DELIVERY_ADDRESS

-- ----------------------------------------------------------------------------------------------------- SHIPMENT_STATUS
SELECT DISTINCT SHIPMENT_STATUS
FROM SHIPMENTS
ORDER BY SHIPMENT_STATUS ASC
;
