create table CUSTOMERS
(
    CUSTOMER_ID   NUMBER generated by default on null as identity
        constraint CUSTOMERS_PK
        primary key,
    EMAIL_ADDRESS VARCHAR2(255 char) not null
        constraint CUSTOMERS_EMAIL_U
            unique,
    FULL_NAME     VARCHAR2(255 char) not null
) /

comment on table CUSTOMERS is 'Details of the people placing orders'
/

comment on column CUSTOMERS.CUSTOMER_ID is 'Auto-incrementing primary key'
/

comment on column CUSTOMERS.EMAIL_ADDRESS is 'The email address the person uses to access the account'
/

comment on column CUSTOMERS.FULL_NAME is 'What this customer is called'
/

create index CUSTOMERS_NAME_I
    on CUSTOMERS (FULL_NAME)
    /

create table STORES
(
    STORE_ID          NUMBER generated by default on null as identity
        constraint STORES_PK
        primary key,
    STORE_NAME        VARCHAR2(255 char) not null
        constraint STORE_NAME_U
            unique,
    WEB_ADDRESS       VARCHAR2(100 char),
    PHYSICAL_ADDRESS  VARCHAR2(512 char),
    LATITUDE          NUMBER(9, 6),
    LONGITUDE         NUMBER(9, 6),
    LOGO              BLOB,
    LOGO_MIME_TYPE    VARCHAR2(512 char),
    LOGO_FILENAME     VARCHAR2(512 char),
    LOGO_CHARSET      VARCHAR2(512 char),
    LOGO_LAST_UPDATED DATE,
    constraint STORE_AT_LEAST_ONE_ADDRESS_C
        check (web_address IS NOT NULL or physical_address IS NOT NULL)
) /

comment on table STORES is 'Physical and virtual locations where people can purchase products'
/

comment on column STORES.STORE_ID is 'Auto-incrementing primary key'
/

comment on column STORES.STORE_NAME is 'What the store is called'
/

comment on column STORES.WEB_ADDRESS is 'The URL of a virtual store'
/

comment on column STORES.PHYSICAL_ADDRESS is 'The postal address of this location'
/

comment on column STORES.LATITUDE is 'The north-south position of a physical store'
/

comment on column STORES.LONGITUDE is 'The east-west position of a physical store'
/

comment on column STORES.LOGO is 'An image used by this store'
/

comment on column STORES.LOGO_MIME_TYPE is 'The mime-type of the store logo'
/

comment on column STORES.LOGO_FILENAME is 'The name of the file loaded in the image column'
/

comment on column STORES.LOGO_CHARSET is 'The character set used to encode the image'
/

comment on column STORES.LOGO_LAST_UPDATED is 'The date the image was last changed'
/

create table PRODUCTS
(
    PRODUCT_ID         NUMBER generated by default on null as identity
        constraint PRODUCTS_PK
        primary key,
    PRODUCT_NAME       VARCHAR2(255 char) not null,
    UNIT_PRICE         NUMBER(10, 2),
    PRODUCT_DETAILS    BLOB
        constraint PRODUCTS_JSON_C
            check (product_details is json),
    PRODUCT_IMAGE      BLOB,
    IMAGE_MIME_TYPE    VARCHAR2(512 char),
    IMAGE_FILENAME     VARCHAR2(512 char),
    IMAGE_CHARSET      VARCHAR2(512 char),
    IMAGE_LAST_UPDATED DATE
) /

comment on table PRODUCTS is 'Details of goods that customers can purchase'
/

comment on column PRODUCTS.PRODUCT_ID is 'Auto-incrementing primary key'
/

comment on column PRODUCTS.PRODUCT_NAME is 'What a product is called'
/

comment on column PRODUCTS.UNIT_PRICE is 'The monetary value of one item of this product'
/

comment on column PRODUCTS.PRODUCT_DETAILS is 'Further details of the product stored in JSON format'
/

comment on column PRODUCTS.PRODUCT_IMAGE is 'A picture of the product'
/

comment on column PRODUCTS.IMAGE_MIME_TYPE is 'The mime-type of the product image'
/

comment on column PRODUCTS.IMAGE_FILENAME is 'The name of the file loaded in the image column'
/

comment on column PRODUCTS.IMAGE_CHARSET is 'The character set used to encode the image'
/

comment on column PRODUCTS.IMAGE_LAST_UPDATED is 'The date the image was last changed'
/

create table ORDERS
(
    ORDER_ID     NUMBER generated by default on null as identity
        constraint ORDERS_PK
        primary key,
    ORDER_TMS    TIMESTAMP(6) not null,
    CUSTOMER_ID  NUMBER       not null
        constraint ORDERS_CUSTOMER_ID_FK
            references CUSTOMERS,
    ORDER_STATUS VARCHAR2(10 char) not null
        constraint ORDERS_STATUS_C
            check (order_status in
                   ('CANCELLED', 'COMPLETE', 'OPEN', 'PAID', 'REFUNDED', 'SHIPPED')),
    STORE_ID     NUMBER       not null
        constraint ORDERS_STORE_ID_FK
            references STORES
) /

comment on table ORDERS is 'Details of who made purchases where'
/

comment on column ORDERS.ORDER_ID is 'Auto-incrementing primary key'
/

comment on column ORDERS.ORDER_TMS is 'When the order was placed'
/

comment on column ORDERS.CUSTOMER_ID is 'Who placed this order'
/

comment on column ORDERS.ORDER_STATUS is 'What state the order is in. Valid values are:
OPEN - the order is in progress
PAID - money has been received from the customer for this order
SHIPPED - the products have been dispatched to the customer
COMPLETE - the customer has received the order
CANCELLED - the customer has stopped the order
REFUNDED - there has been an issue with the order and the money has been returned to the customer'
/

comment on column ORDERS.STORE_ID is 'Where this order was placed'
/

create index ORDERS_CUSTOMER_ID_I
    on ORDERS (CUSTOMER_ID)
    /

create index ORDERS_STORE_ID_I
    on ORDERS (STORE_ID)
    /

create table SHIPMENTS
(
    SHIPMENT_ID      NUMBER generated by default on null as identity
        constraint SHIPMENTS_PK
        primary key,
    STORE_ID         NUMBER not null
        constraint SHIPMENTS_STORE_ID_FK
            references STORES,
    CUSTOMER_ID      NUMBER not null
        constraint SHIPMENTS_CUSTOMER_ID_FK
            references CUSTOMERS,
    DELIVERY_ADDRESS VARCHAR2(512 char) not null,
    SHIPMENT_STATUS  VARCHAR2(100 char) not null
        constraint SHIPMENT_STATUS_C
            check (shipment_status in
                   ('CREATED', 'SHIPPED', 'IN-TRANSIT', 'DELIVERED'))
) /

comment on table SHIPMENTS is 'Details of where ordered goods will be delivered'
/

comment on column SHIPMENTS.SHIPMENT_ID is 'Auto-incrementing primary key'
/

comment on column SHIPMENTS.STORE_ID is 'Which location the goods will be transported from'
/

comment on column SHIPMENTS.CUSTOMER_ID is 'Who this shipment is for'
/

comment on column SHIPMENTS.DELIVERY_ADDRESS is 'Where the goods will be transported to'
/

comment on column SHIPMENTS.SHIPMENT_STATUS is 'The current status of the shipment. Valid values are:
CREATED - the shipment is ready for order assignment
SHIPPED - the goods have been dispatched
IN-TRANSIT - the goods are en-route to their destination
DELIVERED - the good have arrived at their destination'
/

create index SHIPMENTS_STORE_ID_I
    on SHIPMENTS (STORE_ID)
    /

create index SHIPMENTS_CUSTOMER_ID_I
    on SHIPMENTS (CUSTOMER_ID)
    /

create table ORDER_ITEMS
(
    ORDER_ID     NUMBER not null
        constraint ORDER_ITEMS_ORDER_ID_FK
            references ORDERS,
    LINE_ITEM_ID NUMBER not null,
    PRODUCT_ID   NUMBER not null
        constraint ORDER_ITEMS_PRODUCT_ID_FK
            references PRODUCTS,
    UNIT_PRICE   NUMBER(10, 2) not null,
    QUANTITY     NUMBER not null,
    SHIPMENT_ID  NUMBER
        constraint ORDER_ITEMS_SHIPMENT_ID_FK
            references SHIPMENTS,
    constraint ORDER_ITEMS_PK
        primary key (ORDER_ID, LINE_ITEM_ID),
    constraint ORDER_ITEMS_PRODUCT_U
        unique (PRODUCT_ID, ORDER_ID)
) /

comment on table ORDER_ITEMS is 'Details of which products the customer has purchased in an order'
/

comment on column ORDER_ITEMS.ORDER_ID is 'The order these products belong to'
/

comment on column ORDER_ITEMS.LINE_ITEM_ID is 'An incrementing number, starting at one for each order'
/

comment on column ORDER_ITEMS.PRODUCT_ID is 'Which item was purchased'
/

comment on column ORDER_ITEMS.UNIT_PRICE is 'How much the customer paid for one item of the product'
/

comment on column ORDER_ITEMS.QUANTITY is 'How many items of this product the customer purchased'
/

comment on column ORDER_ITEMS.SHIPMENT_ID is 'Where this product will be delivered'
/

create index ORDER_ITEMS_SHIPMENT_ID_I
    on ORDER_ITEMS (SHIPMENT_ID)
    /

create table INVENTORY
(
    INVENTORY_ID      NUMBER generated by default on null as identity
        constraint INVENTORY_PK
        primary key,
    STORE_ID          NUMBER not null
        constraint INVENTORY_STORE_ID_FK
            references STORES,
    PRODUCT_ID        NUMBER not null
        constraint INVENTORY_PRODUCT_ID_FK
            references PRODUCTS,
    PRODUCT_INVENTORY NUMBER not null,
    constraint INVENTORY_STORE_PRODUCT_U
        unique (STORE_ID, PRODUCT_ID)
) /

comment on table INVENTORY is 'Details of the quantity of stock available for products at each location'
/

comment on column INVENTORY.INVENTORY_ID is 'Auto-incrementing primary key'
/

comment on column INVENTORY.STORE_ID is 'Which location the goods are located at'
/

comment on column INVENTORY.PRODUCT_ID is 'Which item this stock is for'
/

comment on column INVENTORY.PRODUCT_INVENTORY is 'The current quantity in stock'
/

create index INVENTORY_PRODUCT_ID_I
    on INVENTORY (PRODUCT_ID)
    /

create view CUSTOMER_ORDER_PRODUCTS as
SELECT o.order_id,
       o.order_tms,
       o.order_status,
       c.customer_id,
       c.email_address,
       c.full_name,
       SUM(oi.quantity * oi.unit_price) order_total,
       LISTAGG(
               p.product_name, ', '
           ON OVERFLOW TRUNCATE '...' WITH COUNT
       )                                WITHIN GROUP ( ORDER BY oi.line_item_id ) items
FROM   orders o
           JOIN   order_items oi
                  ON     o.order_id = oi.order_id
           JOIN   customers c
                  ON     o.customer_id = c.customer_id
           JOIN   products p
                  ON     oi.product_id = p.product_id
GROUP  BY o.order_id, o.order_tms, o.order_status,
          c.customer_id, c.email_address, c.full_name
/

comment on table CUSTOMER_ORDER_PRODUCTS is 'A summary of who placed each order and what they bought'
/

comment on column CUSTOMER_ORDER_PRODUCTS.ORDER_ID is 'The primary key of the order'
/

comment on column CUSTOMER_ORDER_PRODUCTS.ORDER_TMS is 'The date and time the order was placed'
/

comment on column CUSTOMER_ORDER_PRODUCTS.ORDER_STATUS is 'The current state of this order'
/

comment on column CUSTOMER_ORDER_PRODUCTS.CUSTOMER_ID is 'The primary key of the customer'
/

comment on column CUSTOMER_ORDER_PRODUCTS.EMAIL_ADDRESS is 'The email address the person uses to access the account'
/

comment on column CUSTOMER_ORDER_PRODUCTS.FULL_NAME is 'What this customer is called'
/

comment on column CUSTOMER_ORDER_PRODUCTS.ORDER_TOTAL is 'The total amount the customer paid for the order'
/

comment on column CUSTOMER_ORDER_PRODUCTS.ITEMS is 'A comma-separated list naming the products in this order'
/

create view STORE_ORDERS as
SELECT CASE
           grouping_id(store_name, order_status)
           WHEN 1 THEN 'STORE TOTAL'
           WHEN 2 THEN 'STATUS TOTAL'
           WHEN 3 THEN 'GRAND TOTAL'
           END                                     total,
       s.store_name,
       COALESCE(s.web_address, s.physical_address) address,
       s.latitude,
       s.longitude,
       o.order_status,
       COUNT(DISTINCT o.order_id)                  order_count,
       SUM(oi.quantity * oi.unit_price)            total_sales
FROM stores s
         JOIN orders o
              ON s.store_id = o.store_id
         JOIN order_items oi
              ON o.order_id = oi.order_id
GROUP BY GROUPING SETS ( (s.store_name, COALESCE(s.web_address, s.physical_address), s.latitude, s.longitude),
                         (s.store_name, COALESCE(s.web_address, s.physical_address), s.latitude, s.longitude,
                          o.order_status),
                         o.order_status,
    ()
    ) /

comment on table STORE_ORDERS is 'A summary of what was purchased at each location, including summaries each store, order status and overall total'
/

comment on column STORE_ORDERS.TOTAL is 'Indicates what type of total is displayed, including Store, Status, or Grand Totals'
/

comment on column STORE_ORDERS.STORE_NAME is 'What the store is called'
/

comment on column STORE_ORDERS.ADDRESS is 'The physical or virtual location of this store'
/

comment on column STORE_ORDERS.LATITUDE is 'The north-south position of a physical store'
/

comment on column STORE_ORDERS.LONGITUDE is 'The east-west position of a physical store'
/

comment on column STORE_ORDERS.ORDER_STATUS is 'The current state of this order'
/

comment on column STORE_ORDERS.ORDER_COUNT is 'The total number of orders placed'
/

comment on column STORE_ORDERS.TOTAL_SALES is 'The total value of orders placed'
/

create view PRODUCT_REVIEWS as
SELECT p.product_name,
       r.rating,
       ROUND(
               AVG(r.rating) over (
                   PARTITION BY product_name
                   ),
               2
       ) avg_rating,
       r.review
FROM products p,
     JSON_TABLE(
             p.product_details, '$'
         COLUMNS (
                   NESTED PATH '$.reviews[*]'
                       COLUMNS (
                           rating INTEGER PATH '$.rating',
                           review VARCHAR2(4000) PATH '$.review'
                           )
                   )
     ) r /

comment on table PRODUCT_REVIEWS is 'A relational view of the reviews stored in the JSON for each product'
/

comment on column PRODUCT_REVIEWS.PRODUCT_NAME is 'What this product is called'
/

comment on column PRODUCT_REVIEWS.RATING is 'The review score the customer has placed. Range is 1-10'
/

comment on column PRODUCT_REVIEWS.AVG_RATING is 'The mean of the review scores for this product'
/

comment on column PRODUCT_REVIEWS.REVIEW is 'The text of the review'
/

create view PRODUCT_ORDERS as
SELECT p.product_name,
       o.order_status,
       SUM(oi.quantity * oi.unit_price) total_sales,
       COUNT(*)                         order_count
FROM orders o
         JOIN order_items oi
              ON o.order_id = oi.order_id
         JOIN customers c
              ON o.customer_id = c.customer_id
         JOIN products p
              ON oi.product_id = p.product_id
GROUP BY p.product_name,
         o.order_status
             /
         comment on table PRODUCT_ORDERS is 'A summary of the state of the orders placed for each product'
/

comment on column PRODUCT_ORDERS.PRODUCT_NAME is 'What this product is called'
/

comment on column PRODUCT_ORDERS.ORDER_STATUS is 'The current state of these order'
/

comment on column PRODUCT_ORDERS.TOTAL_SALES is 'The total value of orders placed'
/

comment on column PRODUCT_ORDERS.ORDER_COUNT is 'The total number of orders placed'
/
