-- #%L
-- co
-- %%
-- Copyright (C) 2024 - 2025 Jinahya, Inc.
-- %%
-- Licensed under the Apache License, Version 2.0 (the "License");
-- you may not use this file except in compliance with the License.
-- You may obtain a copy of the License at
-- 
--      http://www.apache.org/licenses/LICENSE-2.0
-- 
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.
-- #L%
---
--
-- create table CO.ORDERS
-- (
--     ORDER_ID     NUMBER generated by default on null as identity
--         constraint ORDERS_PK
--             primary key,
--     ORDER_TMS    TIMESTAMP(6)      not null,
--     CUSTOMER_ID  NUMBER            not null
--         constraint ORDERS_CUSTOMER_ID_FK
--             references CO.CUSTOMERS,
--     ORDER_STATUS VARCHAR2(10 char) not null
--         constraint ORDERS_STATUS_C
--             check (order_status in
--                    ('CANCELLED', 'COMPLETE', 'OPEN', 'PAID', 'REFUNDED', 'SHIPPED')),
--     STORE_ID     NUMBER            not null
--         constraint ORDERS_STORE_ID_FK
--             references CO.STORES
-- )
-- /
--
-- comment on table CO.ORDERS is 'Details of who made purchases where'
-- /
--
-- comment on column CO.ORDERS.ORDER_ID is 'Auto-incrementing primary key'
-- /
--
-- comment on column CO.ORDERS.ORDER_TMS is 'When the order was placed'
-- /
--
-- comment on column CO.ORDERS.CUSTOMER_ID is 'Who placed this order'
-- /
--
-- comment on column CO.ORDERS.ORDER_STATUS is 'What state the order is in. Valid values are:
-- OPEN - the order is in progress
-- PAID - money has been received from the customer for this order
-- SHIPPED - the products have been dispatched to the customer
-- COMPLETE - the customer has received the order
-- CANCELLED - the customer has stopped the order
-- REFUNDED - there has been an issue with the order and the money has been returned to the customer'
-- /
--
-- comment on column CO.ORDERS.STORE_ID is 'Where this order was placed'
-- /
--
-- create index CO.ORDERS_CUSTOMER_ID_I
--     on CO.ORDERS (CUSTOMER_ID)
-- /
--
-- create index CO.ORDERS_STORE_ID_I
--     on CO.ORDERS (STORE_ID)
-- /


-- ------------------------------------------------------------------------------------------------------------ ORDER_ID

-- ----------------------------------------------------------------------------------------------------------- ORDER_TMS

-- --------------------------------------------------------------------------------------------------------- CUSTOMER_ID

-- -------------------------------------------------------------------------------------------------------- ORDER_STATUS
SELECT DISTINCT ORDER_STATUS
FROM ORDERS
ORDER BY ORDER_STATUS ASC
;
-- -------------------------------------------------------------------------------------------------------- STORE_ID
