-- #%L
-- sh
-- %%
-- Copyright (C) 2024 - 2025 Jinahya, Inc.
-- %%
-- Licensed under the Apache License, Version 2.0 (the "License");
-- you may not use this file except in compliance with the License.
-- You may obtain a copy of the License at
-- 
--      http://www.apache.org/licenses/LICENSE-2.0
-- 
-- Unless required by applicable law or agreed to in writing, software
-- distributed under the License is distributed on an "AS IS" BASIS,
-- WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing permissions and
-- limitations under the License.
-- #L%
---
--
-- ---------------------------------------------------------------------------------------------------------- COUNTRY_ID
-- ---------------------------------------------------------------------------------------------------- COUNTRY_ISO_CODE
-- -------------------------------------------------------------------------------------------------------- COUNTRY_NAME
-- --------------------------------------------------------------------------------------------------- COUNTRY_SUBREGION
-- ------------------------------------------------------------------------------------------------ COUNTRY_SUBREGION_ID
-- ------------------------------------------------------------------------------------------------------ COUNTRY_REGION
-- --------------------------------------------------------------------------------------------------- COUNTRY_REGION_ID
-- ------------------------------------------------------------------------------------------------------- COUNTRY_TOTAL
-- ---------------------------------------------------------------------------------------------------- COUNTRY_TOTAL_ID
