DROP USER IF EXISTS dmlonly CASCADE;
CREATE USER dmlonly IDENTIFIED BY password
    DEFAULT TABLESPACE SYSTEM
;

GRANT
    CREATE SESSION,
    SELECT ANY TABLE,
    INSERT ANY TABLE,
    UPDATE ANY TABLE,
    DELETE ANY TABLE
    TO dmlonly
;
