package com.github.jinahya.oracle.sample.schemas.persistence.hr;

/*-
 * #%L
 * hr
 * %%
 * Copyright (C) 2024 - 2026 Jinahya, Inc.
 * %%
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * #L%
 */

import org.eclipse.persistence.sequencing.NativeSequence;
import org.eclipse.persistence.sessions.DatabaseLogin;
import org.eclipse.persistence.sessions.Session;
import org.eclipse.persistence.sessions.SessionCustomizer;

import java.sql.Connection;
import java.util.HashMap;

/**
 * A session customizer which points every entity whose table has an Oracle identity column at the sequence Oracle backs
 * that column with.
 * <p>
 * EclipseLink's Oracle platforms do not support identity columns, so EclipseLink implements
 * {@link jakarta.persistence.GenerationType#IDENTITY IDENTITY} with a sequence, named {@code SEQ_GEN_IDENTITY} unless
 * told otherwise, which does not exist. Oracle does back each identity column with a sequence, but names it itself --
 * {@code ISEQ$$_<object number>} -- so the name differs per installation and cannot be written into a mapping. This
 * customizer reads the names from {@code ALL_TAB_IDENTITY_COLS} when the unit is deployed, and gives each such
 * descriptor its own sequence, with an allocation size of one, as the backing sequences increment by one. The value
 * EclipseLink takes from it is inserted explicitly, which the {@code GENERATED BY DEFAULT} columns accept.
 * <p>
 * A descriptor is matched by its qualified table name -- the schema comes from the unit's {@code orm-it.xml} -- so the
 * customizer names no schema itself, and a unit with no identity column is left as it is. The connecting user needs
 * {@code SELECT} on each backing sequence.
 *
 * @author Jin Kwon &lt;onacit_at_gmail.com&gt;
 */
public class _EclipseLink_IdentitySequences implements SessionCustomizer {

    /**
     * Creates a new instance.
     */
    public _EclipseLink_IdentitySequences() {
        super();
    }

    @Override
    public void customize(final Session session) throws Exception {
        // the session is not logged in yet; read the backing sequences through a connection of our own, opened by the
        // login itself, which holds the password encrypted
        final var login = (DatabaseLogin) session.getDatasourceLogin();
        final var sequences = new HashMap<String, String>(); // OWNER.TABLE -> backing sequence name
        try (var connection = (Connection) login.connectToDatasource(null, session);
             var statement = connection.prepareStatement(
                     "SELECT owner, table_name, sequence_name FROM all_tab_identity_cols");
             var results = statement.executeQuery()) {
            while (results.next()) {
                sequences.put(results.getString(1) + '.' + results.getString(2), results.getString(3));
            }
        }
        for (final var descriptor : session.getDescriptors().values()) {
            if (!descriptor.usesSequenceNumbers() || descriptor.getTables().isEmpty()) {
                continue;
            }
            final var name = sequences.get(descriptor.getTables().getFirst().getQualifiedName());
            if (name == null) {
                continue;
            }
            login.addSequence(new NativeSequence(name, 1, false));
            descriptor.setSequenceNumberName(name);
        }
    }
}
